### ISSUE TITLE
Help.  What's your omnet version and INET version for this project?

### ISSUE THREAD

**Issue by codeswolves** [Avian688/leosatellites#12]

**Comment by Avian688** [comment]
Hello, 
I would recommend OMNeT version 5.6. The INET version should not matter. I would also recommend using GCC over clang, which you can change within the configure.user file in your omnet-5.x.x directory. Also, ensure that the OS3 project works as intended by running some of the simulations, as an incorrect importation of the curl library can easily create linking errors, which may affect the leosatellites project. Let me know how this goes.

**Comment by codeswolves** [comment]
thanks a lot, your suggestions are working for me. Problems are addressed. :D
