### ISSUE TITLE
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by codeswolves** [Avian688/leosatellites#13]
Hello, i tried to use leosatellites-master on windows 10, the inet version is 4.2.5.  OS3 is successfuly compiled, but leosatellites-master faces an error "clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)". Is anyone facing the same problem? how to fix it?  many thanks.

**Comment by Avian688** [comment]
Hello, I have replied to your previous comment so please have a go at what I mentioned. I just uploaded a small compatibility fix for Windows, so I would also recommend pulling the recent changes, as this may fix your issue. Many thanks.
