### ISSUE TITLE
Buid leosatellites error

### ISSUE THREAD

**Issue by jinshushi** [Avian688/leosatellites#16]
ubuntu 20.04
omnet 6.0.1
inet 4.4
when i make MODE=release && make MODE=debug, 
networklayer/configurator/ipv4/LeoIpv4NetworkConfigurator.cc:59:13: error: no member named '__fs' in namespace 'std'
    if(std::__fs::filesystem::is_directory(filePrefix) || std::__fs::filesystem::exists(filePrefix)) {

plesae tell me what should i do.

**Comment by Haxk0r** [comment]
Hi, did you find a solution for this and if so could you please share how you resolved this issue?

Much appreciated.
